#!/usr/bin/env python3
"""Download every image referenced by the scraped Squarespace site at full resolution.

Reads docs/scrape/*.json and docs/scrape/*.html, collects every images.squarespace-cdn.com
URL, downloads each one (?format=2500w, falling back to ?format=original, then bare URL)
into assets/img/originals/ and writes assets/img/SOURCES.md.

Usage:  python tools/download-assets.py
"""
import json
import pathlib
import re
import sys
import urllib.parse
from io import BytesIO

import requests
from PIL import Image

ROOT = pathlib.Path(__file__).resolve().parent.parent
SCRAPE = ROOT / "docs" / "scrape"
OUT = ROOT / "assets" / "img" / "originals"
UA = {"User-Agent": "Mozilla/5.0 (site-migration scraper)"}
CDN = re.compile(r'(?:https?:)?//(?:images\.squarespace-cdn\.com|static1\.squarespace\.com)/[^\s"\'<>)]+?\.(?:png|jpe?g|ico|gif|webp|svg)', re.I)


def local_name(url: str) -> str:
    raw = urllib.parse.unquote_plus(url.rsplit("/", 1)[-1].split("?")[0])
    name = raw.lower().replace(" ", "-")
    name = re.sub(r"[()]", "", name)
    name = re.sub(r"-+", "-", name)
    return name


def collect() -> dict[str, set[str]]:
    urls: dict[str, set[str]] = {}
    for f in sorted(SCRAPE.iterdir()):
        if f.suffix not in (".json", ".html"):
            continue
        text = f.read_text(encoding="utf-8", errors="replace")
        for m in CDN.finditer(text):
            u = m.group(0)
            if u.startswith("//"):
                u = "https:" + u
            urls.setdefault(u, set()).add(f.name)
    return urls


def fetch(url: str) -> tuple[bytes, str] | None:
    for suffix in ("?format=2500w", "?format=original", ""):
        try:
            r = requests.get(url + suffix, headers=UA, timeout=120)
        except requests.RequestException as e:
            print(f"   !! {e}")
            continue
        if r.status_code == 200 and r.content:
            return r.content, suffix or "(bare)"
        print(f"   {r.status_code} {url}{suffix}")
    return None


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    urls = collect()
    print(f"{len(urls)} unique asset URLs")
    rows = []
    failed = []
    seen_names: dict[str, bytes] = {}
    for url in sorted(urls, key=local_name):
        name = local_name(url)
        got = fetch(url)
        if not got:
            failed.append(url)
            continue
        data, how = got
        if name in seen_names and seen_names[name] != data:
            stem, ext = name.rsplit(".", 1)
            n = 2
            while f"{stem}-{n}.{ext}" in seen_names:
                n += 1
            name = f"{stem}-{n}.{ext}"
        elif name in seen_names:
            rows.append((name, url, "(duplicate of same file)", ", ".join(sorted(urls[url]))))
            continue
        seen_names[name] = data
        (OUT / name).write_bytes(data)
        try:
            with Image.open(BytesIO(data)) as im:
                dims = f"{im.width}x{im.height}"
        except Exception:
            dims = "?"
        print(f"OK {dims:>10} {how:<17} {name}")
        rows.append((name, url, dims, ", ".join(sorted(urls[url]))))

    md = ["# Image sources", "",
          "Every file in `assets/img/originals/` and the Squarespace URL it was downloaded from.",
          "Requested with `?format=2500w` (Squarespace serves the largest available rendition, capped at 2500 px on the long edge).",
          "Derived WebP renditions in `assets/img/` are generated by `tools/optimise-images.py`.", "",
          "| Local file | Pixel size (as downloaded) | Source URL | Referenced by |", "|---|---|---|---|"]
    for name, url, dims, pages in rows:
        md.append(f"| `{name}` | {dims} | {url} | {pages} |")
    if failed:
        md += ["", "## Failed", ""] + [f"- {u}" for u in failed]
    (ROOT / "assets" / "img" / "SOURCES.md").write_text("\n".join(md) + "\n", encoding="utf-8")
    if failed:
        print("FAILED:", *failed, sep="\n  ", file=sys.stderr)


if __name__ == "__main__":
    main()
